#!/usr/bin/env bash

if [[ $# -eq 0 ]]; then
    selected=$(
    (fd --type d --min-depth 1 --max-depth 2 '' \
        ~/NTNU/h23 ~/NTNU/v24 ~/NTNU/h24 ~/NTNU/Studass ~/NTNU/CTF) \
    | fzf)
else
    echo "Ikke implementert"
fi

if [[ -z $selected ]]; then
    cd .
else
    cd $selected
fi

