#!/usr/bin/env bash

if [[ $# -eq 0 ]]; then
    selected=$(
    (fd --type d --min-depth 1 --max-depth 4 '' \
        ~/NTNU) \
    | fzf)
else
    echo "Ikke implementert"
fi

if [[ -z $selected ]]; then
    cd .
else
    cd $selected
fi

