###########
# Primary #
###########

[colors.primary]
background = "#1E1E1E" # base
foreground = "#CDD6F4" # text   - text
# Bright and dim foreground colors
dim_foreground = "#CDD6F4" # text
bright_foreground = "#CDD6F4" # text

[colors.cursor]
text = "#1E1E2E" # base
cursor =  "#F5E0DC" # rosewater

# Normal colors
[colors.normal]
black =     "#1D2021" # surface1
red =       "#FF5B68" # red           - git branch
green =     "#A6E3A1" # green
yellow =    "#F9E2AF" # yellow
blue =      "#89B4FA" # blue         - git: 
magenta =   "#F5C2E7" # pink
cyan =      "#94E2D5" # teal         - current folder
white =     "#BAC2DE" # subtext1

    # Bright colors
[colors.bright]
black = "#585B70" # surface2
red = "#F38BA8" # red
green = "#A6E3A1" # green
yellow = "#F9E2AF" # yellow
blue = "#89B4FA" # blue
magenta = "#F5C2E7" # pink
cyan = "#94E2D5" # teal
white = "#A6ADC8" # subtext0

    # Dim colors
[colors.dim]
black = "#45475A" # surface1
red = "#F38BA8" # red
green = "#A6E3A1" # green
yellow = "#F9E2AF" # yellow
blue = "#89B4FA" # blue
magenta = "#F5C2E7" # pink
cyan = "#94E2D5" # teal
white = "#BAC2DE" # subtext1
